# These are supported funding model platforms

github: ['ANON-SYS-INC', 'thisismydesign']
patreon: ANON SYS, INC.
open_collective: ANON SYS, INC.
ko_fi: ANON SYS, INC.
community_bridge: ANON SYS, INC.
liberapay: ANON SYS, INC.
issuehunt: ANON SYS, INC.
otechie: ANON SYS, INC.
custom: ['BTC-ADDR：bc1qv3yuhsqhs2wjstjqj6va3z84pvrar8jkme3der', 'ETH-ADDR：0x4CA3002dfA8145d7C57486e61581A363680F277c', 'XMR-ADDR：4AjwE2amUShWWe7Y5NbVbHcCaRVbftubyaMgy69MRjSWMyGa5XUgnfaS7Bncu1Et3RCLASN1k4vG1a5raoJS4uhqMdPXXoe']