# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Basic Configuration
encoding: UTF-8
locale: en-US
title: "ANON SYS, INC."
keyword: "ANON SYS, INC."
email: 0XE7BC5E3W@onion.org
organization: "ANON SYS, INC."
description: >- # this means to ignore newlines until "baseurl:"
  WE ARE ANON SYS. WE ARE LEGION.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/assets/resource/icon/favicon/icon-32x32.png"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##
##

test:
  -
    href_1: /OpenAPIs/ServerlessEngine/PaaS/Container/XXX/Publicized/
    href_2: /PublicizedAPIs/ServerlessEngine/SaaS/Container/XXX/Actions=Serverless/Reaction=Process/Publicized/Services/Exchange/FluidExchange
    href_3: /OpenAPIs/ServerlessEngine/DBaaS/Container/XXX/Actions=Serverless/Reaction=Process/Publicized/Services/Exchange/FluidExchange
    href_4: /OpenAPIs/ServerlessEngine/FaaS/Container/XXX/Actions=Serverless/Reaction=Process/Publicized/Services/Exchange/FluidExchange
    href_5: Actions=GlobalToken/Reaction=OAuth-Keys/Privatized/Services/Global-Plans/Pull-Requests=PreviewPlans/NBM
    href_6: Reaction=Actions/Publicized/Services/XXX | watch?v=IGyX98EzG3g | Events | Lives
    label_1: ANON-INC/i18n/EN/Breaking-News/Breaking-News.yaml
    label_2: ANON-INC/i18n/EN/Top-News/Top-News.yaml
    label_3: ANON-INC/common/i18n/EN/xxxx
    label_4: ANON-INC/common/i18n/CN/xxxx
    label_5: Actions=GlobalToken/Reaction=OAuth-Keys/Privatized/Services/Knowledge-Graph/Biz-Knowledge-Graph/Start-Biz/USA-美国
    label_6: Actions=GlobalToken/Reaction=OAuth-Keys/Privatized/Services/Knowledge-Graph/Biz-Knowledge-Graph/Start-Biz/CHN-中国
    label_7: Actions=GlobalToken/Reaction=OAuth-Keys/Privatized/Services/Knowledge-Graph/Biz-Knowledge-Graph/Start-Biz/JPN-日本
    label_8: Actions=GlobalToken/Reaction=OAuth-Keys/Privatized/Services/Knowledge-Graph/Biz-Knowledge-Graph/Start-Biz/KOR-韩国
    label_9: Actions=GlobalToken/Reaction=OAuth-Keys/Privatized/Services/Knowledge-Graph/Biz-Knowledge-Graph/Start-Biz/UK-英国
    label_10: Actions=GlobalToken/Reaction=OAuth-Keys/Privatized/Services/Knowledge-Graph/Biz-Knowledge-Graph/Start-Biz/RUS-俄罗斯
    label_11: Actions=GlobalToken/Reaction=OAuth-Keys/Privatized/Services/Knowledge-Graph/Biz-Knowledge-Graph/Start-Biz/ESP-西班牙
    label_12: Actions=GlobalToken/Reaction=OAuth-Keys/Privatized/Services/Knowledge-Graph/Biz-Knowledge-Graph/Start-Biz/KSA-沙特阿拉伯


#  ────────────────────────(START AUTOMATED BUILD SERVICE)─────────────────────────────────

# PaaS Containers VMS-0XPTO Configuration
remote_network_vm_for_anon_inc_title: ANON SYS, INC.
remote_network_vm_for_anon_inc_description: WE ARE ANON SYS. WE ARE LEGION.
remote_network_vm_for_anon_inc_favicon: "/OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/icon/favicon/icon-32x32.png"
remote_network_vm_for_anon_inc_base_network: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC
remote_network_vm_for_anon_inc_base_addr: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/
remote_network_vm_for_anon_inc_base_static_addr: /OpenAPIs/ServerlessEngine/PaaS/Containers/VMS-0XPTO/ANON-INC/assets/resource/

navs:
  -
    href: /
    label: Home
  -
    href: /activity
    label: Activity
  -
    href: /explore
    label: Explore
  -
    href: /enterprise
    label: Enterprise
  -
    href: /marketplace
    label: Marketplace
#  ────────────────────────(END AUTOMATED BUILD SERVICE)──────────────────────────────────