# Basic Configuration
encoding: UTF-8
locale: en-US
baseurl: ""
title: "ANON SYS, INC."
SEOTitle: "ANON SYS, INC."
email: 0XE7BC5E3W@onion.org
description: "WE ARE ANON SYS. WE ARE LEGION."
keyword: "ANON SYS, INC."
organization: "ANON SYS, INC."
url: ""
favicon: "/assets/resource/icon/favicon/icon-32x32.png"

# Build settings
theme: minima
plugins:
  - jekyll-feed